[build]
  command = "pip install matplotlib==3.7.0 numpy==1.24.2 pandas==1.5.3 Pillow==9.4.0 && streamlit run resume.py"
  publish = "Resume/streamlit_build"

[build.environment]
PYTHON_VERSION = "3.8"
LIBRARY_PATH = "/opt/buildhome/python3.8/lib"
LD_LIBRARY_PATH = "/opt/buildhome/python3.8/lib"
