[build]
  command = "pip install matplotlib==3.4.2 numpy==1.21.5 pandas==1.3.5 Pillow==9.0.0 && streamlit run resume.py"
  publish = "Resume/streamlit_build"

[build.environment]
  PYTHON_VERSION = "3.8"
