[build]
  publish = "streamlit_Resume"
  command = "pip install -r requirements.txt && streamlit run resume.py"

[context.production.environment]
  PYTHONHASHSEED = "0"
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_SERVER_ENABLE_CORS = "false"
